Update postman.zip link
CMSgov/dpc-static-site pull request #66
Opened 2022-07-18 17:56 UTC by lgarceau768

### Fixes [DPC-2456](https://jira.cms.gov/browse/DPC-2456)
Fixes the incorrect link shown in the Postman Collection Documentation

### Proposed Changes
Update the link in the documentation tab of the Postman collection, then export it, finally replace the `postman.zip` in the repository with the new files.

### Change Details
- updated the postman documentation from `https://dpc.cms.gov/docs#upload-your-first-public-key` to 'https://dpc.cms.gov/docsV1#upload-your-first-public-key`

### Acceptance Validation
Open the compressed zip file and check the collection documentation within postman. I was able to fully test this.

2022-07-21 14:42 UTC, TiannaW24 submitted a review, later dismissed

2022-07-21 15:16 UTC, mftcodes commented
There are two other places this needs to be changed. Same line as your current change just a little further, and on line 129 under a "description" for another section in the same file.

2022-07-21 15:16 UTC, mftcodes requested changes
See comments in conversation section. There are two other places this needs to be updated, it appears.

2022-08-31 20:27 UTC, mftcodes approved these changes
Check zip and all looks good! Approved!

2022-08-31 20:28 UTC, merged